### ISSUE TITLE
Above your nn.py have some problems.

### ISSUE THREAD

**Issue by JH95-ai** [jahongir7174/EfficientNetV2#2]
In your python file nets/nn.py.
I think your class SE for realize SE(squeeze and Excitation).Why your __init__() haven't  avgpool for squeeze,And self.se use conv2d. did not nn.linear().
Looking forward to your reply.

**Comment by jahongir7174** [comment]
1. Instead of using avg pool, I used [mean](https://github.com/jahongir7174/EffcientNetV2/blob/3ad86b179d3a78bfcbbe1591ef13b3d5f5298bd7/nets/nn.py#L95)
2. It is a modified version of the SE layer not the original. You can refer [reference implementation](https://github.com/keras-team/keras-applications/blob/bc89834ed36935ab4a4994446e34ff81c0d8e1b7/keras_applications/efficientnet.py#L172)
